import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import GlobalProviders from "@/components/globalProviders";
import Script from "next/script";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GlobalProviders>{children}</GlobalProviders>
        <Script
          src="https://cdn.ckbox.io/ckbox/2.6.1/ckbox.js"
          crossOrigin="anonymous"
        ></Script>
        <Toaster position="bottom-right" />
      </body>
    </html>
  );
}
